//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AuditoriaTSS.wsServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AuditoriaWsSoap", Namespace="http://tempuri.org/")]
    public partial class AuditoriaWs : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProcesaBusquedaAfiliados_Ws_BsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesaBusquedaAfiliados_Adicional_Ws_BsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcesaBusquedaImagenes_Ws_BsOperationCompleted;
        
        private System.Threading.SendOrPostCallback transferir_sql_Ws_BsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreaNuevaAuditoria_Ws_BsOperationCompleted;
        
        private System.Threading.SendOrPostCallback validaExitimagenes_Ws_BsOperationCompleted;
        
        private System.Threading.SendOrPostCallback validaExitimagenesRad_Ws_BsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarAuditoria_Ws_BsOperationCompleted;
        
        private System.Threading.SendOrPostCallback dtbus_especifica_Ws_BsOperationCompleted;
        
        private System.Threading.SendOrPostCallback dtbus_pol_radic_Ws_BsOperationCompleted;
        
        private System.Threading.SendOrPostCallback dtbus_pol_radic_especific_Ws_BsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AuditoriaWs() {
            this.Url = global::AuditoriaTSS.Properties.Settings.Default.AuditoriaTSS_wsServices_AuditoriaWs;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcesaBusquedaAfiliados_Ws_BsCompletedEventHandler ProcesaBusquedaAfiliados_Ws_BsCompleted;
        
        /// <remarks/>
        public event ProcesaBusquedaAfiliados_Adicional_Ws_BsCompletedEventHandler ProcesaBusquedaAfiliados_Adicional_Ws_BsCompleted;
        
        /// <remarks/>
        public event ProcesaBusquedaImagenes_Ws_BsCompletedEventHandler ProcesaBusquedaImagenes_Ws_BsCompleted;
        
        /// <remarks/>
        public event transferir_sql_Ws_BsCompletedEventHandler transferir_sql_Ws_BsCompleted;
        
        /// <remarks/>
        public event CreaNuevaAuditoria_Ws_BsCompletedEventHandler CreaNuevaAuditoria_Ws_BsCompleted;
        
        /// <remarks/>
        public event validaExitimagenes_Ws_BsCompletedEventHandler validaExitimagenes_Ws_BsCompleted;
        
        /// <remarks/>
        public event validaExitimagenesRad_Ws_BsCompletedEventHandler validaExitimagenesRad_Ws_BsCompleted;
        
        /// <remarks/>
        public event ActualizarAuditoria_Ws_BsCompletedEventHandler ActualizarAuditoria_Ws_BsCompleted;
        
        /// <remarks/>
        public event dtbus_especifica_Ws_BsCompletedEventHandler dtbus_especifica_Ws_BsCompleted;
        
        /// <remarks/>
        public event dtbus_pol_radic_Ws_BsCompletedEventHandler dtbus_pol_radic_Ws_BsCompleted;
        
        /// <remarks/>
        public event dtbus_pol_radic_especific_Ws_BsCompletedEventHandler dtbus_pol_radic_especific_Ws_BsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcesaBusquedaAfiliados_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ProcesaBusquedaAfiliados_Ws_Bs(int codigoauditoria) {
            this.Invoke("ProcesaBusquedaAfiliados_Ws_Bs", new object[] {
                        codigoauditoria});
        }
        
        /// <remarks/>
        public void ProcesaBusquedaAfiliados_Ws_BsAsync(int codigoauditoria) {
            this.ProcesaBusquedaAfiliados_Ws_BsAsync(codigoauditoria, null);
        }
        
        /// <remarks/>
        public void ProcesaBusquedaAfiliados_Ws_BsAsync(int codigoauditoria, object userState) {
            if ((this.ProcesaBusquedaAfiliados_Ws_BsOperationCompleted == null)) {
                this.ProcesaBusquedaAfiliados_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesaBusquedaAfiliados_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("ProcesaBusquedaAfiliados_Ws_Bs", new object[] {
                        codigoauditoria}, this.ProcesaBusquedaAfiliados_Ws_BsOperationCompleted, userState);
        }
        
        private void OnProcesaBusquedaAfiliados_Ws_BsOperationCompleted(object arg) {
            if ((this.ProcesaBusquedaAfiliados_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesaBusquedaAfiliados_Ws_BsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcesaBusquedaAfiliados_Adicional_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ProcesaBusquedaAfiliados_Adicional_Ws_Bs(int codigoauditoria) {
            this.Invoke("ProcesaBusquedaAfiliados_Adicional_Ws_Bs", new object[] {
                        codigoauditoria});
        }
        
        /// <remarks/>
        public void ProcesaBusquedaAfiliados_Adicional_Ws_BsAsync(int codigoauditoria) {
            this.ProcesaBusquedaAfiliados_Adicional_Ws_BsAsync(codigoauditoria, null);
        }
        
        /// <remarks/>
        public void ProcesaBusquedaAfiliados_Adicional_Ws_BsAsync(int codigoauditoria, object userState) {
            if ((this.ProcesaBusquedaAfiliados_Adicional_Ws_BsOperationCompleted == null)) {
                this.ProcesaBusquedaAfiliados_Adicional_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesaBusquedaAfiliados_Adicional_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("ProcesaBusquedaAfiliados_Adicional_Ws_Bs", new object[] {
                        codigoauditoria}, this.ProcesaBusquedaAfiliados_Adicional_Ws_BsOperationCompleted, userState);
        }
        
        private void OnProcesaBusquedaAfiliados_Adicional_Ws_BsOperationCompleted(object arg) {
            if ((this.ProcesaBusquedaAfiliados_Adicional_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesaBusquedaAfiliados_Adicional_Ws_BsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcesaBusquedaImagenes_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ProcesaBusquedaImagenes_Ws_Bs(int CodigoAuditoria, string app) {
            object[] results = this.Invoke("ProcesaBusquedaImagenes_Ws_Bs", new object[] {
                        CodigoAuditoria,
                        app});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ProcesaBusquedaImagenes_Ws_BsAsync(int CodigoAuditoria, string app) {
            this.ProcesaBusquedaImagenes_Ws_BsAsync(CodigoAuditoria, app, null);
        }
        
        /// <remarks/>
        public void ProcesaBusquedaImagenes_Ws_BsAsync(int CodigoAuditoria, string app, object userState) {
            if ((this.ProcesaBusquedaImagenes_Ws_BsOperationCompleted == null)) {
                this.ProcesaBusquedaImagenes_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcesaBusquedaImagenes_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("ProcesaBusquedaImagenes_Ws_Bs", new object[] {
                        CodigoAuditoria,
                        app}, this.ProcesaBusquedaImagenes_Ws_BsOperationCompleted, userState);
        }
        
        private void OnProcesaBusquedaImagenes_Ws_BsOperationCompleted(object arg) {
            if ((this.ProcesaBusquedaImagenes_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcesaBusquedaImagenes_Ws_BsCompleted(this, new ProcesaBusquedaImagenes_Ws_BsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/transferir_sql_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void transferir_sql_Ws_Bs(int codAuditoria, string app, string tipo) {
            this.Invoke("transferir_sql_Ws_Bs", new object[] {
                        codAuditoria,
                        app,
                        tipo});
        }
        
        /// <remarks/>
        public void transferir_sql_Ws_BsAsync(int codAuditoria, string app, string tipo) {
            this.transferir_sql_Ws_BsAsync(codAuditoria, app, tipo, null);
        }
        
        /// <remarks/>
        public void transferir_sql_Ws_BsAsync(int codAuditoria, string app, string tipo, object userState) {
            if ((this.transferir_sql_Ws_BsOperationCompleted == null)) {
                this.transferir_sql_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.Ontransferir_sql_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("transferir_sql_Ws_Bs", new object[] {
                        codAuditoria,
                        app,
                        tipo}, this.transferir_sql_Ws_BsOperationCompleted, userState);
        }
        
        private void Ontransferir_sql_Ws_BsOperationCompleted(object arg) {
            if ((this.transferir_sql_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transferir_sql_Ws_BsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreaNuevaAuditoria_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreaNuevaAuditoria_Ws_Bs(int TipoBusqueda, string FormaBusqueda) {
            object[] results = this.Invoke("CreaNuevaAuditoria_Ws_Bs", new object[] {
                        TipoBusqueda,
                        FormaBusqueda});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreaNuevaAuditoria_Ws_BsAsync(int TipoBusqueda, string FormaBusqueda) {
            this.CreaNuevaAuditoria_Ws_BsAsync(TipoBusqueda, FormaBusqueda, null);
        }
        
        /// <remarks/>
        public void CreaNuevaAuditoria_Ws_BsAsync(int TipoBusqueda, string FormaBusqueda, object userState) {
            if ((this.CreaNuevaAuditoria_Ws_BsOperationCompleted == null)) {
                this.CreaNuevaAuditoria_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreaNuevaAuditoria_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("CreaNuevaAuditoria_Ws_Bs", new object[] {
                        TipoBusqueda,
                        FormaBusqueda}, this.CreaNuevaAuditoria_Ws_BsOperationCompleted, userState);
        }
        
        private void OnCreaNuevaAuditoria_Ws_BsOperationCompleted(object arg) {
            if ((this.CreaNuevaAuditoria_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreaNuevaAuditoria_Ws_BsCompleted(this, new CreaNuevaAuditoria_Ws_BsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/validaExitimagenes_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int validaExitimagenes_Ws_Bs(int cod_auditoria) {
            object[] results = this.Invoke("validaExitimagenes_Ws_Bs", new object[] {
                        cod_auditoria});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void validaExitimagenes_Ws_BsAsync(int cod_auditoria) {
            this.validaExitimagenes_Ws_BsAsync(cod_auditoria, null);
        }
        
        /// <remarks/>
        public void validaExitimagenes_Ws_BsAsync(int cod_auditoria, object userState) {
            if ((this.validaExitimagenes_Ws_BsOperationCompleted == null)) {
                this.validaExitimagenes_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidaExitimagenes_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("validaExitimagenes_Ws_Bs", new object[] {
                        cod_auditoria}, this.validaExitimagenes_Ws_BsOperationCompleted, userState);
        }
        
        private void OnvalidaExitimagenes_Ws_BsOperationCompleted(object arg) {
            if ((this.validaExitimagenes_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validaExitimagenes_Ws_BsCompleted(this, new validaExitimagenes_Ws_BsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/validaExitimagenesRad_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int validaExitimagenesRad_Ws_Bs(int cod_auditoria) {
            object[] results = this.Invoke("validaExitimagenesRad_Ws_Bs", new object[] {
                        cod_auditoria});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void validaExitimagenesRad_Ws_BsAsync(int cod_auditoria) {
            this.validaExitimagenesRad_Ws_BsAsync(cod_auditoria, null);
        }
        
        /// <remarks/>
        public void validaExitimagenesRad_Ws_BsAsync(int cod_auditoria, object userState) {
            if ((this.validaExitimagenesRad_Ws_BsOperationCompleted == null)) {
                this.validaExitimagenesRad_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidaExitimagenesRad_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("validaExitimagenesRad_Ws_Bs", new object[] {
                        cod_auditoria}, this.validaExitimagenesRad_Ws_BsOperationCompleted, userState);
        }
        
        private void OnvalidaExitimagenesRad_Ws_BsOperationCompleted(object arg) {
            if ((this.validaExitimagenesRad_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validaExitimagenesRad_Ws_BsCompleted(this, new validaExitimagenesRad_Ws_BsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarAuditoria_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ActualizarAuditoria_Ws_Bs(int codigoauditoria) {
            this.Invoke("ActualizarAuditoria_Ws_Bs", new object[] {
                        codigoauditoria});
        }
        
        /// <remarks/>
        public void ActualizarAuditoria_Ws_BsAsync(int codigoauditoria) {
            this.ActualizarAuditoria_Ws_BsAsync(codigoauditoria, null);
        }
        
        /// <remarks/>
        public void ActualizarAuditoria_Ws_BsAsync(int codigoauditoria, object userState) {
            if ((this.ActualizarAuditoria_Ws_BsOperationCompleted == null)) {
                this.ActualizarAuditoria_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarAuditoria_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("ActualizarAuditoria_Ws_Bs", new object[] {
                        codigoauditoria}, this.ActualizarAuditoria_Ws_BsOperationCompleted, userState);
        }
        
        private void OnActualizarAuditoria_Ws_BsOperationCompleted(object arg) {
            if ((this.ActualizarAuditoria_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarAuditoria_Ws_BsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtbus_especifica_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable dtbus_especifica_Ws_Bs(string tipo, string Valor1, string Valor2, string Valor3, string Valor4, string Valor5) {
            object[] results = this.Invoke("dtbus_especifica_Ws_Bs", new object[] {
                        tipo,
                        Valor1,
                        Valor2,
                        Valor3,
                        Valor4,
                        Valor5});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void dtbus_especifica_Ws_BsAsync(string tipo, string Valor1, string Valor2, string Valor3, string Valor4, string Valor5) {
            this.dtbus_especifica_Ws_BsAsync(tipo, Valor1, Valor2, Valor3, Valor4, Valor5, null);
        }
        
        /// <remarks/>
        public void dtbus_especifica_Ws_BsAsync(string tipo, string Valor1, string Valor2, string Valor3, string Valor4, string Valor5, object userState) {
            if ((this.dtbus_especifica_Ws_BsOperationCompleted == null)) {
                this.dtbus_especifica_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondtbus_especifica_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("dtbus_especifica_Ws_Bs", new object[] {
                        tipo,
                        Valor1,
                        Valor2,
                        Valor3,
                        Valor4,
                        Valor5}, this.dtbus_especifica_Ws_BsOperationCompleted, userState);
        }
        
        private void Ondtbus_especifica_Ws_BsOperationCompleted(object arg) {
            if ((this.dtbus_especifica_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dtbus_especifica_Ws_BsCompleted(this, new dtbus_especifica_Ws_BsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtbus_pol_radic_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void dtbus_pol_radic_Ws_Bs(string tipoBusqueda, int codauditoria, System.Data.DataTable dt) {
            this.Invoke("dtbus_pol_radic_Ws_Bs", new object[] {
                        tipoBusqueda,
                        codauditoria,
                        dt});
        }
        
        /// <remarks/>
        public void dtbus_pol_radic_Ws_BsAsync(string tipoBusqueda, int codauditoria, System.Data.DataTable dt) {
            this.dtbus_pol_radic_Ws_BsAsync(tipoBusqueda, codauditoria, dt, null);
        }
        
        /// <remarks/>
        public void dtbus_pol_radic_Ws_BsAsync(string tipoBusqueda, int codauditoria, System.Data.DataTable dt, object userState) {
            if ((this.dtbus_pol_radic_Ws_BsOperationCompleted == null)) {
                this.dtbus_pol_radic_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondtbus_pol_radic_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("dtbus_pol_radic_Ws_Bs", new object[] {
                        tipoBusqueda,
                        codauditoria,
                        dt}, this.dtbus_pol_radic_Ws_BsOperationCompleted, userState);
        }
        
        private void Ondtbus_pol_radic_Ws_BsOperationCompleted(object arg) {
            if ((this.dtbus_pol_radic_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dtbus_pol_radic_Ws_BsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dtbus_pol_radic_especific_Ws_Bs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void dtbus_pol_radic_especific_Ws_Bs(string tipoBusqueda, int codauditoria, string valor) {
            this.Invoke("dtbus_pol_radic_especific_Ws_Bs", new object[] {
                        tipoBusqueda,
                        codauditoria,
                        valor});
        }
        
        /// <remarks/>
        public void dtbus_pol_radic_especific_Ws_BsAsync(string tipoBusqueda, int codauditoria, string valor) {
            this.dtbus_pol_radic_especific_Ws_BsAsync(tipoBusqueda, codauditoria, valor, null);
        }
        
        /// <remarks/>
        public void dtbus_pol_radic_especific_Ws_BsAsync(string tipoBusqueda, int codauditoria, string valor, object userState) {
            if ((this.dtbus_pol_radic_especific_Ws_BsOperationCompleted == null)) {
                this.dtbus_pol_radic_especific_Ws_BsOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondtbus_pol_radic_especific_Ws_BsOperationCompleted);
            }
            this.InvokeAsync("dtbus_pol_radic_especific_Ws_Bs", new object[] {
                        tipoBusqueda,
                        codauditoria,
                        valor}, this.dtbus_pol_radic_especific_Ws_BsOperationCompleted, userState);
        }
        
        private void Ondtbus_pol_radic_especific_Ws_BsOperationCompleted(object arg) {
            if ((this.dtbus_pol_radic_especific_Ws_BsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dtbus_pol_radic_especific_Ws_BsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ProcesaBusquedaAfiliados_Ws_BsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ProcesaBusquedaAfiliados_Adicional_Ws_BsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ProcesaBusquedaImagenes_Ws_BsCompletedEventHandler(object sender, ProcesaBusquedaImagenes_Ws_BsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcesaBusquedaImagenes_Ws_BsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcesaBusquedaImagenes_Ws_BsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void transferir_sql_Ws_BsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CreaNuevaAuditoria_Ws_BsCompletedEventHandler(object sender, CreaNuevaAuditoria_Ws_BsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreaNuevaAuditoria_Ws_BsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreaNuevaAuditoria_Ws_BsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void validaExitimagenes_Ws_BsCompletedEventHandler(object sender, validaExitimagenes_Ws_BsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validaExitimagenes_Ws_BsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validaExitimagenes_Ws_BsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void validaExitimagenesRad_Ws_BsCompletedEventHandler(object sender, validaExitimagenesRad_Ws_BsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validaExitimagenesRad_Ws_BsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validaExitimagenesRad_Ws_BsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ActualizarAuditoria_Ws_BsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void dtbus_especifica_Ws_BsCompletedEventHandler(object sender, dtbus_especifica_Ws_BsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dtbus_especifica_Ws_BsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dtbus_especifica_Ws_BsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void dtbus_pol_radic_Ws_BsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void dtbus_pol_radic_especific_Ws_BsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591